import "@styles/global.css";
export const metadata = {
  title: "Connect Together",
  description: "Generated by Next.js",
  icons: {
    icon: "/assets/favicon.png", // Ensure this file exists in the `public` folder
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
